#!/usr/bin/env python3
"""Marveen Message Bus — Pydantic schemas for typed A2A communication."""

from enum import Enum
from typing import Any, Optional
import time
import uuid

from pydantic import BaseModel, Field, model_validator


class MessageType(str, Enum):
    """Message intent classification — determines how the receiving agent processes it."""

    REQUEST_DATA = "request_data"  # e.g. "Study, give me the file path for X"
    HANDOFF = "handoff"  # Delegate a task to another agent
    CLARIFICATION = "clarification"  # "I don't understand, help me interpret"
    STATUS_UPDATE = "status_update"  # "Report done, here's the result"
    ALERT = "alert"  # "⚠️ Gateway is down!"
    TASK_DELEGATION = "task_delegation"  # General → Dev: "do X"
    AUTO_REPLY = "auto_reply"  # Bridge-generated automatic reply — NEVER trigger further auto-replies


# TTL mapping: how long a message lives based on priority
PRIORITY_TTL = {
    0: 86400,  # 24 hours (normal)
    1: 3600,  # 1 hour (high)
    2: 900,  # 15 minutes (urgent)
}


class SendBusMessage(BaseModel):
    """Strictly typed A2A message bus schema — with production hardening.

    Every inter-agent message sent via send_bus_message MUST conform to this schema.
    Pydantic validation enforces field types, ranges, and patterns before the message
    ever hits the database.

    Production hardening features:
      - idempotency_key: UUID v4 prevents duplicate processing
      - correlation_id + parent_message_id: causal trace tree
      - expires_at: auto-calculated TTL from priority
      - max_retries: DLQ threshold
    """

    # === Required core fields ===
    target_agent_id: str = Field(
        ...,
        description=(
            "Target agent identifier: 'general', 'dev', 'research', 'study', "
            "or any dynamically registered agent name"
        ),
        min_length=1,
        max_length=64,
        pattern=r"^[a-z][a-z0-9_-]*$",
    )
    message_type: MessageType = Field(
        ...,
        description="The intent of the message. Determines how the receiving agent processes it.",
    )
    payload: dict[str, Any] = Field(
        ...,
        description=(
            "Structured data or natural language query. MUST contain 'summary' "
            "(one-sentence summary) and 'body' (detailed content) keys. "
            "Optional: 'context' (structured metadata)."
        ),
    )
    priority: int = Field(
        default=0,
        ge=0,
        le=2,
        description="Priority: 0=normal, 1=high, 2=urgent",
    )

    # === Production hardening fields ===
    idempotency_key: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description=(
            "UUID v4 — unique key for deduplication. Generated by sender. "
            "The DB unique constraint prevents the same key from being processed twice."
        ),
        pattern=r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
    )
    correlation_id: Optional[int] = Field(
        default=None,
        description=(
            "The root message ID of this conversation chain. "
            "None if this is the first message — will be set to its own ID after DB insert."
        ),
    )
    parent_message_id: Optional[int] = Field(
        default=None,
        description=(
            "The immediate parent message ID. None if this is the first message. "
            "Together with correlation_id, forms the causal trace tree."
        ),
    )
    expires_at: Optional[float] = Field(
        default=None,
        description=(
            "Unix timestamp after which the message is invalid and the router "
            "will not deliver it. Auto-calculated from priority if None: "
            "P0=+24h, P1=+1h, P2=+15min."
        ),
    )
    max_retries: int = Field(
        default=3,
        ge=0,
        le=10,
        description=(
            "Max delivery retry attempts before the message is moved to "
            "dead letter queue (status='dead'). 0 = no retries."
        ),
    )

    # === Auto-reply / chain depth fields ===
    chain_depth: int = Field(
        default=0,
        ge=0,
        le=10,
        description=(
            "How many auto-reply hops this message is deep from the original. "
            "0 = original user/agent message. Incremented by 1 for each auto-reply. "
            "LLM Bridges refuse to auto-reply if depth >= MAX_CHAIN_DEPTH."
        ),
    )
    reply_to: Optional[int] = Field(
        default=None,
        description=(
            "The immediate message ID this is a reply to. "
            "None if this is an original (non-reply) message."
        ),
    )

    @model_validator(mode="after")
    def validate_payload_and_expiry(self):
        """Validate payload has required keys and auto-set expiry."""
        # Payload must contain 'summary' and 'body'
        if not isinstance(self.payload, dict):
            raise ValueError("payload must be a dict")
        if "summary" not in self.payload or "body" not in self.payload:
            raise ValueError("payload must contain 'summary' and 'body' keys")
        # Auto-set expires_at
        if self.expires_at is None:
            object.__setattr__(self, "expires_at", time.time() + PRIORITY_TTL.get(self.priority, 86400))
        return self
